baseurl: "/dsa-puddles" # the subpath of your site, e.g. /blog

# Paginate
paginate: 9
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "raintale-templates", "vendor", "scripts", "hidden"]
